AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SaaSWAF - Board API (Serverless)

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 10
    MemorySize: 256
  Api:
    Auth:
      ApiKeyRequired: true

Resources:

  # DynamoDB 테이블
  BoardTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BoardTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
              
  GetNewsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get-news
      CodeUri: src/news/
      Handler: getNews.handler
      Runtime: nodejs18.x
      Events:
        GetNewsAPI:
          Type: Api
          Properties:
            Path: /api/news
            Method: GET
            Auth:
              ApiKeyRequired: true
      Policies:
        - S3ReadPolicy:
            BucketName: your-s3-bucket-name

Outputs:

  BoardApiUrl:
    Description: "Board API Gateway URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
