AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SaaSWAF - Board API (Serverless)

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 10
    MemorySize: 256
  Api:
    Auth:
      ApiKeyRequired: true

Resources:
  NoticeTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: NoticeTable
      PrimaryKey:
        Name: id
        Type: String
      BillingMode: PAY_PER_REQUEST

  GetNoticeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: notice/getNotice.handler
      Runtime: nodejs18.x
      Events:
        GetNoticeAPI:
          Type: Api
          Properties:
            Path: /notice
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref NoticeTable
      Environment:
        Variables:
          TABLE_NAME: !Ref NoticeTable

  CreateNoticeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: notice/createNotice.handler
      Runtime: nodejs18.x
      Events:
        CreateNoticeAPI:
          Type: Api
          Properties:
            Path: /notice
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NoticeTable
      Environment:
        Variables:
          TABLE_NAME: !Ref NoticeTable