AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SaaSWAF - Board API (Serverless)

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 10
    MemorySize: 256
  Api:
    Auth:
      ApiKeyRequired: true

Resources:
  GetNoticesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: notice/getNotices.handler
      Runtime: nodejs18.x
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /notice
            Method: GET
  CreateNoticeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: notice/createNotice.handler
      Runtime: nodejs18.x
      Events:
        PostApi:
          Type: Api
          Properties:
            Path: /notice
            Method: POST

Outputs:

  BoardApiUrl:
    Description: "Board API Gateway URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
